### ISSUE TITLE
Implementing Quick sort 

### ISSUE THREAD

**Issue by Siddhesh4501** [dsrao711/DSA-Together-HacktoberFest#10]

**Comment by Siddhesh4501** [comment]
Can you please assign it to me?

**Comment by dsrao711** [comment]
Sure @Siddhesh4501 . Go ahead!

**Comment by iam-monu** [comment]
can you assign this project to me I can add code in python ,c++ and js

**Comment by dsrao711** [comment]
@iam-monu , Since this repo focuses on Python solutions, c++ and js wont be added . 
Will be creating new issues , you can get yourself assigned others

**Comment by iam-monu** [comment]
thank you!

**Comment by kambleaa007** [comment]
I think its closed now
