### ISSUE TITLE
Pattern Questions

### ISSUE THREAD

**Issue by iam-monu** [dsrao711/DSA-Together-HacktoberFest#12]
Can you assign this issue to me Pattern problem in c++

**Comment by dsrao711** [comment]
I can assign this to you but the solution has to be in Python. Works?

**Comment by iam-monu** [comment]
yes I can do it in python also

**Comment by dsrao711** [comment]
Cool. I am assigning this to you.
Make sure you read the 'CONTRIBUTING.md'  and follow the guidelines.
