### ISSUE TITLE
Backspace String compare , Provide solution with O(1) space - Two pointer algorithm

### ISSUE THREAD

**Issue by dsrao711** [dsrao711/DSA-Together-HacktoberFest#17]
**Is your feature request related to a problem? Please describe.**
Link to the problem :  https://leetcode.com/problems/backspace-string-compare/

**Describe the solution you'd like**
Provide Two pointer approach for this problem

Create a file "backspace_string_compare.py" in the TwoPointer folder and add your solution.

**Comment by akarsh-jain-790** [comment]
Can you assign this to me?

**Comment by dsrao711** [comment]
Sure . Go ahead @akarsh-jain-790

**Comment by dsrao711** [comment]
Are you still working on this ? @akarsh-jain-790

**Comment by KrishanKantAgnihotri** [comment]
hey can you assign this issue to me?

**Comment by akarsh-jain-790** [comment]
> Are you still working on this ? @akarsh-jain-790

No, you can close the issue

**Comment by KrishanKantAgnihotri** [comment]
we can add cpp solution?

**Comment by krishnak3101** [comment]
I can do it in Python. Please assign it to me.
