### ISSUE TITLE
Bubble sort Algorithm 

### ISSUE THREAD

**Issue by dsrao711** [dsrao711/DSA-Together-HacktoberFest#2]
- Provide a python solution for the bubble sort algorithm 
- Mention the Time and Space complexity at the end of the code 
- Add the code in Algorithms/BubbleSort/bubble_sort.py file

**Comment by disha4u** [comment]
Can this issue be assigned to me @dsrao711

**Comment by dsrao711** [comment]
Ya sure . Go ahead @disha4u

**Comment by Siddhesh4501** [comment]
Can I do this

**Comment by dsrao711** [comment]
@Siddhesh4501 , @disha4u is already working on this issue . You can go through the repo and create a new issue or choose another unassigned issue.
