### ISSUE TITLE
Split a string in Balanced Strings

### ISSUE THREAD

**Issue by dsrao711** [dsrao711/DSA-Together-HacktoberFest#21]
Link for the problem : https://leetcode.com/problems/split-a-string-in-balanced-strings/

Add your code in the 'split_string_in_balanced_string' .
Mention the time complexity at the end 
It would be great if you can write the approach before coding , go through other files for reference

**Comment by Vaishnavi-Markunde** [comment]
Hello , I would like to work on this issue, could you please assign it to me

**Comment by dsrao711** [comment]
Yes sure , go ahead
