### ISSUE TITLE
Valid anagram - Hashmap approach 

### ISSUE THREAD

**Issue by dsrao711** [dsrao711/DSA-Together-HacktoberFest#22]
Link : https://leetcode.com/problems/valid-anagram/

Go to the 'valid_anagram.py' in the Strings/Easy Folder 
Add the Hashmap approach 
Mention the time and space complexities 
Go through the CONTRIBUTING.md file and follow the guidelines

**Comment by pragneshmangukiya** [comment]
please assign to me

**Comment by dsrao711** [comment]
Go ahead

**Comment by Ridhikalra** [comment]
@dsrao711 Please assign this issue to me.

**Comment by dsrao711** [comment]
Ya sure . Go ahead @Ridhikalra
