### ISSUE TITLE
Longest substring without repeating charachters

### ISSUE THREAD

**Issue by dsrao711** [dsrao711/DSA-Together-HacktoberFest#25]
Link : https://leetcode.com/problems/longest-substring-without-repeating-characters/

Create a file in 'Strings/Medium' folder  and add your code .

Dont forget to check the 'CONTRIBUTING.md' File for guidelines

**Comment by rushil180101** [comment]
Hello, can I take this issue ?

**Comment by dsrao711** [comment]
Sure
