### ISSUE TITLE
Python Program to check Armstrong Number

### ISSUE THREAD

**Issue by KrishanKantAgnihotri** [dsrao711/DSA-Together-HacktoberFest#30]
Armstrong Numbers solution which is there in Arrays folder works for only numbers with three digits.
You can look to the list of Armstrong Numbers here .
https://mathworld.wolfram.com/NarcissisticNumber.html

**Comment by dsrao711** [comment]
Add the code in 'Arrays/armstrong.py'

**Comment by dsrao711** [comment]
@KrishanKantAgnihotri Would you like to work on this ?

**Comment by KrishanKantAgnihotri** [comment]
Yes

**Comment by dsrao711** [comment]
Go ahead

**Comment by KrishanKantAgnihotri** [comment]
PR sent
