### ISSUE TITLE
Check If Circular Linked List 

### ISSUE THREAD

**Issue by dsrao711** [dsrao711/DSA-Together-HacktoberFest#4]
Link : https://practice.geeksforgeeks.org/problems/circular-linked-list/1

Create a file 'check_if_circular_linked_list' in the Linked List folder and submit your code

**Comment by namitaarya** [comment]
Can I take this up? Would be my first PR :)

**Comment by dsrao711** [comment]
Sure @namitaarya . Go ahead

**Comment by dsrao711** [comment]
Do check the 'CONTRIBUTING.md' for contribution guidelines
