### ISSUE TITLE
Find the middle element of Linked List 

### ISSUE THREAD

**Issue by dsrao711** [dsrao711/DSA-Together-HacktoberFest#5]
Link  : https://leetcode.com/problems/middle-of-the-linked-list/

Create a new file 'middle_ele_of_linked_list' in the Linked List folder and add your code.

**Comment by darshilagrawal** [comment]
Can you assign this to me ?

**Comment by raazanand** [comment]
hey @dsrao711! I would like to work on this problem.

**Comment by dsrao711** [comment]
@darshilagrawal . Go ahead

**Comment by dsrao711** [comment]
@raazanand . Issues are assigned on First come first serve basis .You can check other issues or create new one and get yourself assigned one

**Comment by dsrao711** [comment]
Are you still working on this @darshilagrawal

**Comment by darshilagrawal** [comment]
Yes was stuck with my internship work, will raise the PR by tonight. Thanks for checking up

**Comment by dsrao711** [comment]
Cool
