### ISSUE TITLE
Second most repeated string in a sequence

### ISSUE THREAD

**Issue by simran2002** [dsrao711/DSA-Together-HacktoberFest#54]
Hi @dsrao711, greetings 
I would like to add a solution to this problem
https://practice.geeksforgeeks.org/problems/second-most-repeated-string-in-a-sequence0534/1

Please assign this task to me.

Reference: DSA 450 sheet by Love Babbar
Thanks and Regards

**Comment by dsrao711** [comment]
Go ahead!
