### ISSUE TITLE
Explain Linked Lists , Can we reverse a linked List in less than o(n)

### ISSUE THREAD

**Issue by dsrao711** [dsrao711/DSA-Together-HacktoberFest#7]
- Explain LinkedList and use cases
- Can we reverse a linked List in less than o(n)
- Add your explanation in LinkedList.md file in LinkedList folder

**Comment by neodark** [comment]
Can you assign me this one please?

**Comment by nkhandelwal07** [comment]
can you assign me this?

**Comment by dsrao711** [comment]
Sure @neodark . Go ahead !
